### ISSUE TITLE
What do we do with `max_cum_in_unit_flow_bound`?

### ISSUE THREAD

**Issue by manuelma** [spine-tools/SpineOpt.jl#355]
The earliest commit I was able to track this back is c560a88910aea2b6237c57cbf6d2d0f62e214485

There're two TODOs in the code:

```
TODO: How to turn this one into stochastic one? Path indexing over the whole `unit_group`?
TODO: Calling `max_cum_in_unit_flow_bound[(unit=ug)]` fails.
```

The questions are, do we need this constraint, and who wants to revise/update it?

**Comment by mihlema** [comment]
My take on this:
- Yes we need it (and probably even more than just this), in order to being able to e.g. set an upper bound on emissions for the optimization. There should probably also be corresponding `min_in & min/max_out` flow bounds 
- Currently, the only thing we do is to sum everything over a unit_group, but I believe it needs to be something like (ug,ng), so unit group and node group in order to achieve the above functionality. Or possibly even better to use commodity here?
- Regarding the error, I haven't reproduced it but I *think* it has something to do with the `[]` operator combined with groups of objects

**Comment by manuelma** [comment]
Thanks @mihlema 

It looks like a full refactoring is needed. For this reason, I propose to get rid of it momentarily as it is really unusable at the moment. Then, whenever somebody has time to work on this, they can add it back. What do you think?

**Comment by mihlema** [comment]
I'll work on refactoring it this week, I think we can leave it in the code for the moment

**Comment by DillonJ** [comment]
I really think we need to rename this parameter / constraint and I'm also hoping we don't need to get into too much of a discussion regarding why :-)

**Comment by mihlema** [comment]
completely agree, any suggestions?
`maximum_cumulated_unit_flows__to_node`
`maximum_cumulated_unit_flows__from_node`
`maximum_cumulated_net_unit_flows` ?

(I think we should also change `unit/connection_conv_cap_to_flow`. It also doesn't seems to be self-explaining at all)

**Comment by mihlema** [comment]
@KristofPhillips95 I believe this relates to our discussion we had on e.g. renewable targets? Would you be comfortable picking this one up?
An addition from our other issue on this topic (#180): What needs to be considered is over which period are we cummulating these parameters? (always per year or per optimization window (i.e. longest temporal block) or per model horizon, others?)

**Comment by clizbe** [comment]
Closing due to stale status.

**Comment by clizbe** [comment]
Closing because stale.
