### ISSUE TITLE
Support investments for nodal lossless DC powerflow

### ISSUE THREAD

**Issue by mihlema** [spine-tools/SpineOpt.jl#359]
With the recent merge #353, we support node-based lossless DC power flow with node voltage angles. Investments in such connections are not yet supported. To add this functionality, we'd need some revision/advances to the current code. This should be added whenever there are resources available.

**Comment by DillonJ** [comment]
This is pretty cool - I didn't realise that this change was bringing in angle based DC load flow. It's nice to have the choice of both PTDF and angle based DC load flow - we should try and make sure we have a nice way of choosing between both options.

Supporting investments for angle based DC load flow should be relatively straightforward since the angles are variables and it should be more straight forward than PTDF load flow investments. In fact, I think the only thing we might need to do is to change the conditions where the investment variable is activated in constraint_connection_flow_capacity

**Comment by clizbe** [comment]
Closing due to stale status.

**Comment by clizbe** [comment]
Closing because stale.
