### ISSUE TITLE
Does `fix_node_state` need to consider `storages_invested_available`?

### ISSUE THREAD

**Issue by CIODWYER** [spine-tools/SpineOpt.jl#389]
Related to the closed issue #215 At the moment fix_node_state for investments is not multiplied by storages_invested_available as, based on previous discussions, it was assumed that newly invested storages should be empty. This makes sense for multi-year investments, but if you are including seasonal storage and want to represent 1 year of typical operation starting at 0 makes less sense, but introducing this brings back the problem of free energy discussed in the last issue.

**Comment by DillonJ** [comment]
I've been thinking about this some more... I've found in a model that I'm working on, that the initial value you choose for a storage influence the optimal value of other things in the model. We could make the initial volume of an existing storage or a candidate storage an investment variable also with a cost - choosing this cost would be difficult though as it would really be an output of the model.

Another thing we could do is, as per the original topic, make fix_node_state relative but factor in the energy cost to the investment cost of the storage so this initial energy doesn't come for free.

We could do similar to the above but create a new parameter, intial_investment_state (or something) that does the same job and leave fix_node_state as it is and add a simple constraint.

Any thoughts? @mihlema @jkiviluo @manuelma @Tasqu @CIODWYER ?

**Comment by DillonJ** [comment]
Nice ideas @jkiviluo 

I'm having interesting issues with models with lots of zero marginal cost units and storage. Since there is no marginal cost, the model doesn't see any value in storing it. For example, if you have two ways of producing energy, one more efficient than the other, the model doesn't care if it's all zero-cost anyway - unless you attribute some value even small, to the stored energy.

**Comment by jkiviluo** [comment]
Right, I don't think there is any other way around it than to give it a small marginal cost (or long enough horizon so that there is some use for that stored energy). A similar issue is when the model uses a storage to destroy energy by charging and discharging at the same time (assuming a loss). You can limit that to some extent with linear constraints, but it really requires a binary variable to fully prevent simultaneous charging and discharging. It can happen when there are e.g. subsidies for VRE generation.

**Comment by clizbe** [comment]
Closing due to stale status.

**Comment by clizbe** [comment]
Closing because stale.
