### ISSUE TITLE
Consider removing report as output data dimension

### ISSUE THREAD

**Issue by DillonJ** [spine-tools/SpineOpt.jl#430]
Report is added as a dimension to output data. When there is only one report (vast majority of cases in my experience), then this is superflous because the output data is all tagged with a unique alternative.

The only real reason for it that I can see is when there is more than one report. In these cases, why not create a unique alternative instead, for each report.

In the vast majority of cases, report is an unecessary dimension to the output data that can cause clutter and confusion for users and results in inconveniently long class names.

#429 relates.

**Comment by mihlema** [comment]
What happens if we have 2 models in one database, which are somewhat linked through an algorithm within SpineOpt. Both of the models have e.g. a `variable units_on["Wind", "deterministic", "2000 ~> 2001"]`. I believe at the moment the only way to tell the results apart would be through different report objects.

**Comment by clizbe** [comment]
Due to Maren's opposition and inactivity, I'm closing this as unplanned for now.
