### ISSUE TITLE
Parallel solve of dual LP problem

### ISSUE THREAD

**Issue by DillonJ** [spine-tools/SpineOpt.jl#463]
We are solving large models and we need constraint marginal values - so we need the final dual LP solve. We find that this can take nearly as long as the original MIP solve. It seems like this solve could be carried out in parallel while the model continues with the next window. Initial experiments have shown that this can work but it needs some more testing to make sure it is robust.

**Comment by manuelma** [comment]
> It seems like this solve could be carried out in parallel while the model continues with the next window

The thing is, when the model continues with the next window, all time slices are rolled forward. This means that if the results of the LP solve arrive *after* the model has rolled, they will be written to the wrong indices in the result. To get around this, we now write 'promises' of the result of the dual LP before even start solving it. These promises are written to the correct time indices because the model hasn't roll yet. Once they're written, the model is free to roll. And the promises contain references to the relevant constraint and variables for which we want to compute the marginal values.

All we need to do then is, at the moment of writing results, collect the promises which involves waiting on all the spawned dual solves, and then calling JuMP.dual or JuMP.reduced_const on the stored references. It work nice, but of course it needs to be combined with `write_as_roll` greater than 1 for a speedup to be seen (otherwise we'd be waiting on the dual solve at every window so no parallelization).

All test pass so I just pushed the above solution to master.

**Comment by DillonJ** [comment]
Also a thought , I guess this works and we get max benefit if write_as_roll =0?

**Comment by manuelma** [comment]
> Also a thought , I guess this works and we get max benefit if write_as_roll =0?

Exactly, then we write once at the end.
