### ISSUE TITLE
Forced outages

### ISSUE THREAD

**Issue by manuelma** [spine-tools/SpineOpt.jl#478]
I would like to have the possibility to simulate forced outages in SpineOpt. Initially, I would just like to specify exponentially distributed mean time to failure and mean time to repair for unit and connection. In preprocessing, SpineOpt would translate this into an availability factor time series between model start and model end.

**Comment by DillonJ** [comment]
I’m thinking this would be better as a companion tool… maybe part of the SoineOpt plugin. The reason is that you might run a lot of scenarios but you want the forced outages to be the same for all, so you just want to run it once and that’s all. But you may also want to run it each time as part of the workflow and in that case the tool would allow you to do it as a once off or each time. This might also be the seeds of a reliability model

**Comment by manuelma** [comment]
I see @DillonJ - that's a good point about using the same outages for multiple scenarios... So, outages *must* be generated beforehand and stored somewhere.

I'm thinking the following:
1. Add a new public function to SpineOpt.jl to generate forced outages based on mean time to failure and repair. The function would receive url_in and url_out similar to run_spineopt, where url_out=url_in by default.
2. Add a new parameter called `forced_outages` to the `unit` and `connection` class, to be specified either manually or automatically by calling the function above.
3. In pre-processing, take the information from the `forced_outages` parameter value and update `unit/connection_availability_factor` accordingly.

What do you think?

**Comment by manuelma** [comment]
Also done.
