### ISSUE TITLE
rolling not work with units having input flow

### ISSUE THREAD

**Issue by nnhjy** [spine-tools/SpineOpt.jl#512]
When a typical dispatchable `unit`, which has an input flow from a (fuel) `node` and an output flow to a (demand) `node`, runs in a model using rolling, it only produces output in the first `rolling window` attached to the model. For the following times within the model's horizon, the `unit` doesn't produce output while the demand `node` would rather introduce slacks with a high penalty cost. In contrast, the `unit` works normally in the non-rolling mode. And there is no problem for non-dispatchable units of which the output is defined by `TimeSeries` values.

Try this mini example [Main Input Data Store.zip](https://github.com/Spine-project/SpineOpt.jl/files/10423850/Main.Input.Data.Store.zip) to see the problem. The `BAL_gas` unit has the mentioned issue, and the `BAL_wind-on` unit is the work-as-usual non-dispatchable.

**Comment by josefkoell** [comment]
This problem also occurs when using roll_forward on a storage node. The unit takes out the fuel, and in the first time step, it is also deducted, however, after that, the storage level drops to 0, but the unit continues to take fuel from the node even though it is 0.

**Comment by DillonJ** [comment]
Hi @nnhjy 

Is this perhaps the issue... your gas node has no balance type specified, so the default will be balance_type_node... normally - this means that any flow from the node to your BAL_gas unit needs to come from somewhere. You also have node_state = true for the gas node and there is no fix_node_state to fix the initial condition. This means that in the first rolling window, the model can adjust the history node_state variable and use this energy to supply to your BAL_gas unit. However, it only creates the amount of energy it needs in that first rolling window... in the second window it can't use this trick because your initial fix_node_state will be set to it's value at the end of window 1 which I'm sure is zero.

The solution is to set balance_type = balance_type_none for your gas node... I think?

**Comment by DillonJ** [comment]
Hi @nnhjy. Can we conclude this is not an issue with SpineOpt?

**Comment by DillonJ** [comment]
Thanks @nnhjy I'll close this for now
