### ISSUE TITLE
Better, more consistent treatment of temporal resolutions in User Constraints

### ISSUE THREAD

**Issue by lilanger** [spine-tools/SpineOpt.jl#531]
Hi,
I am not quite sure if this is intended behaviour, but when adding a user constraint to restrict units_invested of a set of units, the constraint adds a multiplier (in my case the investment period 364D * 24) for all the time units (hours). So, I added a Big-M to the RHS, but I was wondering if there is an application for that or if it might be a mistake. Somehow there are different time_blocks used in the constraint...

 user_constraint(user_constraint = NH3-inv-single, stochastic_path = SpineInterface.Object[realization], t = 2018-01-02T00:00~>2019-01-01T00:00) : 
	+ 8736 units_invested[NH3_syn, realization, 2018-01-02T00:00~>2019-01-01T00:00] 
	+ 8736 units_invested[NH3_syn_5, realization, 2018-01-02T00:00~>2019-01-01T00:00] 
	+ 8736 units_invested[NH3_syn_6, realization, 2018-01-02T00:00~>2019-01-01T00:00] 
	+ 8736 units_invested[NH3_syn_7, realization, 2018-01-02T00:00~>2019-01-01T00:00] ≤ 8736.0
 user_constraint(user_constraint = NH3-inv-single, stochastic_path = SpineInterface.Object[realization], t = 2019-01-01T00:00~>2019-12-31T00:00) : 
	+ 8736 units_invested[NH3_syn, realization, 2019-01-01T00:00~>2019-12-31T00:00] 
	+ 8736 units_invested[NH3_syn_5, realization, 2019-01-01T00:00~>2019-12-31T00:00] 
	+ 8736 units_invested[NH3_syn_6, realization, 2019-01-01T00:00~>2019-12-31T00:00] 
	+ 8736 units_invested[NH3_syn_7, realization, 2019-01-01T00:00~>2019-12-31T00:00] ≤ 8736 .0

constraint: https://github.com/spine-tools/SpineOpt.jl/blob/master/src/constraints/constraint_user_constraint.jl
...
            + expr_sum(
                (   
                    + units_invested_available[u, s, t1]
                    * units_invested_available_coefficient[(user_constraint=uc, unit=u, stochastic_scenario=s, analysis_time=t0, t=t1)]
                    + units_invested[u, s, t1]
                    * units_invested_coefficient[(user_constraint=uc, unit=u, stochastic_scenario=s, analysis_time=t0, t=t1)]
                )
                * min(duration(t1), duration(t)) for u in unit__user_constraint(user_constraint=uc)
                for (u, s, t1) in units_invested_available_indices(m; unit=u, stochastic_scenario=s, t=t_overlaps_t(m; t=t));
                init=0,
            )
...

![image](https://user-images.githubusercontent.com/54096244/218791545-5139b087-1e66-4923-a846-4fca99f1b6e5.png)

**Comment by DillonJ** [comment]
Hi Lissy,

A couple of points here:
 - regarding the temporal blocks and the reported time intervals - each time the model rolls, the constraint coefficients are updated but actually renaming the time slices each time the model rolls is quite costly, so we don't do it by default, but you can turn it on by calling `run_spineopt(... , update_names=true)`
 - Potentially your constraint can involve different variables and temporal resolutions, so the coefficients are multiplied by the duration of their corresponding timeslices. There are times we want this, for example when the value represents a cost or energy, but I guess there are times also when we don't want it. But the net result is the same in your case, since RHS is mutiplied by the same duration... so I'm wondering why you need Big-M? Maybe you would have needed it anyway?

**Comment by DillonJ** [comment]
Actually, I'm thinking perhaps we should have two sets of parameters for specifying coefficients - one set which are multiplied by the duration of the timeslice and one which aren't.

**Comment by lilanger** [comment]
Hi Jody,
initially, I put a 1 at the RHS as I would for yearly time aggregation. The multiplier prevented it from working so I already set the the RHS to a "converted value" but I had to check the model to see why it did not work and then adjust the RHS.
![image](https://user-images.githubusercontent.com/54096244/218800189-6f4ce434-2da0-45de-b1a8-1e7623a8a05f.png)

**Comment by lilanger** [comment]
> Actually, I'm thinking perhaps we should have two sets of parameters for specifying coefficients - one set which are multiplied by the duration of the timeslice and one which aren't.

This "hidden" multiplication makes it a bit tricky, I would assume people would do that if needed either for the parameter or the RHS.

**Comment by lilanger** [comment]
> Ah, ok - yeah - this isn't ideal as if you run the model for a different period of time, it might not work

Yes, that is true so if the RHS would automatically be "converted" it might also work... Just not sure if it breaks in other applications then.

**Comment by DillonJ** [comment]
@lilanger maybe we can rename this issue "Better, more consistent treament of temporal resolution in User Constraints.

I think a simple fix that should work in most cases is to multiply the RHS by the duration of the lowest resolution TB, which should ensure consistency in most cases - but we would need to think it through

**Comment by mihlema** [comment]
Possibly also relates to #480. I think the user constraint needs a bit of refurbishment. 

I like the idea @DillonJ of choosing what happens to the aggregation of a variable. I think we had an issue on that as well somewhere. Ideally we would have a flag on one of the variable involved which sets at which resolution the other variables get aggregated or disaggegated. By default it could be e.g. the lowest resolution as implemented now.

**Comment by lilanger** [comment]
Could we just link a specific temporal block to the specific user constraint? The default temporal block would be the default one then. I think that would be most intuitive because as Jodi said one could think of cases where e.g. annual or hourly resolutions would be needed.

**Comment by manuelma** [comment]
We could do that, but I think that could lead to confusion if e.g. the unit is associated to a bunch of temporal blocks and then the user constraint is associated to totally different temporal blocks. Who wins? Maybe I missed your point though...

But regardless, there was a clear inconsistency in the constraint that needed to be fixed - the left hand side was scaled by the duration of the time slice, the right hand side wasn't. Maybe that didn't fix this issue so I'm reopening.

**Comment by lilanger** [comment]
Yes, this would fix my problem because it translates my annual RHS into an hourly one (so making it coherent). But what if one actually wants an hourly parameter such as when invested then sth. hourly (such as min load or whatever)? This is not possible anymore now, I guess...

**Comment by manuelma** [comment]
I think it might be possible but it's now up to the user to compute the rhs they need for that specific thing to happen. My reasoning for the 'fix' I just implemented was to make it coherent/consistent, so the user knows that the duration of the time slice is factored in 'on both sides of the equation' rather than just in one of them.

**Comment by lilanger** [comment]
Yes, I was actually very surprised that it was hourly since all the (investment) variables in the user constraint are annual. Maybe depending on where the development of the user constraints is heading, one could keep the temporal blocks in mind.

**Comment by manuelma** [comment]
Makes sense. So the problem we were having is the following: We wanted a user_constraint of the form: units_on >= 19 (for example). And the relevant units were associated to three different temporal blocks with different resolutions: 15 minutes, 1 hour, and 1 day.

So in the period of time with 15 minutes resolution, the constraint was 0.25 * units_on >= 19

In the period with 1 hour resolution, it was units_on >= 19 (correct)

In the period with 1 day resolution, it was 24 * units_on >= 19

So clearly, this wasn't good because there wasn't a single number to multiply the right hand side with in order to get the right expression regardless of the resolution. We could have used a renewing time series but that seemed crazy.

But after multiplying the rhs by the time slice duration too, we got the right constraint all the time. I am convinced the user would expect it to work this way.

@lilanger what do you think? What other cases would you like the constraint to handle? We could work together in the design if you like.

**Comment by lilanger** [comment]
That makes sense, yes, I agree the LHS and RHS should be consistent. Still, one would have to know for which of the three to formulate the RHS parameter, so there the temporal block might come in, e.g. units_invested[1] + units_invested[2] <= 1,  I was surprised this was hourly. And I still think there might be cases such as a min_op where one wants units_invested to set a lower bound on units_on? I am not sure this would be possible in user constraints...
I am happy to help, though I think I still do not get the full functionality spectrum of the user constraints.

**Comment by clizbe** [comment]
Closed by #560
