### ISSUE TITLE
Explain PTDF-based investments are correct for only 1 line

### ISSUE THREAD

**Issue by jkiviluo** [spine-tools/SpineOpt.jl#602]
Explain that PTDF based investments are correct only for one line. If there are more and those interact, then reactances (?) will start to go wrong and the results become increasingly more incorrect. Should be explained in the documentation to make users aware. And mention that the angle based investments work anyway but is slower (and won't have N-1).

**Comment by clizbe** [comment]
@tarskul If you understand this, would you mind adding it to the docs? You're good at explaining things. :)

**Comment by tarskul** [comment]
@clizbe I'm not too familiar with PTDF in SpineOpt (and it has been a while since I last worked with PTDF in general) but I'm willing to learn and as I learn I can indeed document what I learned. However, I don't think that I will put this high on my priority list, so it may take a while before I get to it. In the meanwhile we can add a warning note.
