### ISSUE TITLE
Add How to Section to Documentation

### ISSUE THREAD

**Issue by DillonJ** [spine-tools/SpineOpt.jl#618]
We have discussed many times that the current documentation is good as a reference when you know what you are looking for - but it it's not so good at explaining how to do specific high-level things that might involve multiple elements.

For example, how to change the solver (https://github.com/spine-tools/SpineOpt.jl/issues/616) or how to define an efficiency (https://github.com/spine-tools/SpineOpt.jl/discussions/617).

I was thinking that we could add a "How To" section to the documentation and add articles which in many cases the content may exist already in issues or discussions. Ideally, it would be pretty easy to add these articles so they can be easily added to over time. For example, if we could have a how to folder and just drop in MD files of the relevant how_to article and the contents/index could be generated automatically based on the contents of the How To folder.

The two issues/discussions above would be a great start.

I have added an issue label "Add how to article to docs" so we can tag issues that may have useful content for a how-to article.

**Comment by tarskul** [comment]
It seems that @jkiviluo has recently added a tutorial section to the documentation. Momentarily this section contains examples like the a5 test case (which I suppose should then be removed from the getting started section?). Would this be equivalent to the "How To" section you had in mind? To me it could make sense to add the topics you proposed to this tutorial section. Or do we think it needs to be separate?

**Comment by tarskul** [comment]
Also, in the same vein, do we make a separate "developer notes" section where we collect some notes on the design decisions within the project. For example the explanation of the code as provided in the recent meetup we had (regarding the multiple run_spineopt functions) or the explanation in Gitter that @manuelma gave might be worth keeping. I.e., the question and the answer:

Q: I'm wondering why square brackets are needed in ratio[(unit=u, node1=ng1, node2=ng2, stochastic_scenario=s, analysis_time=t0, t=t)] (constraint_ratio_unit_flow.jl). This would suggest that ratio is a vector. When I call ratio(unit=u,node1=ng1, node2=ng2), I get a number, as it should be. Furthermore there is ratio.name, which suggests that ratio is of structure type.

A: ratio is of Parameter type. You can find the definition in SpineInterface.jl/src/types.jl. Also, if you look at SpineInterface.jl/src/base.jl you will see that we implement Base.getindex for the Parameter type. The julia parser 'converts' x[y] to Base.getindex(x, y) as you may know. So when we write ratio[something] in our constraint code, we are actually calling Base.getindex(ratio, something). Now if you look at the definition of Base.getindex for Parameter in SpineInterface.jl/src/base.jl, you will see that we return a special object of type Call. The Call object is able to remember the parameter and the namedtuple it was called with. This is what allows SpineOpt models to update themselves automatically as the model rolls. By building constraints and objective with Call objects instead of just numbers, we are able to reevalute the Calls after the model rolls and retrieve the new values. This is all pretty sophisticated and has grown more and more sophisticated over the years in the original Spine project and before Mopo. I am available for a call if you want to learn all these details more in depth...

**Comment by jkiviluo** [comment]
I think there is a difference between tutorials and how-tos. They should therefore be two separate sections. Tutorials are longer and explain how to setup a system from start to finish. How-tos focus on specific issue that is typical for modelling. They can assume that the user knows the basics.

A section on design decisions and practical explainers would be great too. Shouldn't be called 'developer notes' since they can be useful for others than developers too. Maybe 'Concept and code explainers'

**Comment by tarskul** [comment]
For now we have a branch which includes all the suggested changes in the documentation. However, I still might look into the option to allow for a drag and drop process for adding new how to sections (as suggested in the first comment in this issue).

**Comment by tarskul** [comment]
For the drag and drop feature I've chosen an approach that allows both manually composed chapters and automatically generated chapters. To activate the drag and drop feature simply replace the `Any[]` list (which maps the page titles to the markdown files) with `nothing`. For those chapters you can then simply add your markdown file to the folder of the chapter and it will be automatically added to the documentation. I've activated this feature (in the drag and drop branch) for the how to section and another new section called implementation details.
