### ISSUE TITLE
Test successful building of documentation

### ISSUE THREAD

**Issue by Tasqu** [spine-tools/SpineOpt.jl#626]
Currently, when building the documentation there are warnings about potential mistakes in the documentation like broken references etc.

These should probably be changed to errors and tested, so that the unit tests only pass if the documentation is complete.

**Comment by tarskul** [comment]
I've taken a look at the warnings and I see about 3 types of warnings.

1. There are different descriptions for parameters with the same name. At first glance they all seem to originate from the 'to/from' construction, e.g. connection_capacity of connection__to_node and connection__from_node. The warning is not triggered for unit_capacity because it has the same description in unit__to_node and unit__from_node. The easy solution is to copy paste the description of the duplicates (although a similar issue might appear in the future of the project). As for an alternative, it would make sense to allow two different descriptions but that might require the docs_utils file to become smarter (and requires some additional maintenance in the documentation as you have to change stuff in two locations).
2. There are parameters which do not have documentation. You would expect that this would be mostly for relatively new features. And indeed, that seems to be the case for the one example I checked: connection_flow_non_anticipativity_margin which has been added last year by @DillonJ.
3. There are 2 broken references. The first is fix_ratio_out_out which might just be a changed section. Could it be that it should refer to fix_ratio_out_out_unit_flow instead? The second is constraint_max_cum_in_unit_flow_bound which might just be another missing concept. As the reference is not in one of the oldest files (2021 @mihlema) it might just be that the section was planned but not written.

**Comment by Tasqu** [comment]
The duplicate description issue I vaguely remember encountering when automating the building of the documentation. That I don't find as critical as points 2. and 3. which I still think should fail the unit tests to provide developers feedback that something is missing.

**Comment by tarskul** [comment]
This will be resolved in the documentation overhaul #882
