### ISSUE TITLE
Keep documentation for current implementations

### ISSUE THREAD

**Issue by nnhjy** [spine-tools/SpineOpt.jl#647]
Concerning the documentation of some formulations and functionalities that have recently been removed in commits 6ccbb14, 46eda5e, 17a3d14, 3f00373, I suggest we restore and keep them for now for the reasons that 
1) the rollout of the new implementation still needs some time 
2) the current implementation as such still exists and works. 

The users would appreciate those clues on what is going on at the moment. And it would not be too late to replace them with the new ones with the PR for new implementation. WDYT?

**Comment by tarskul** [comment]
Confusion was exactly the reason why they were removed in the first place. It is not necessarily that the formulation was incorrect but the formulation combined different conditions into one formulation making people who are not used to the code and the formulation believe that the formulation was incorrect (e.g. upward and downward spinning reserves in the same equation even though they never show up in the same equation during runtime as only parts of the equation are activated at the same time). So, it is probably best that at the very least they are clarified before returning them (or we wait for the new changes which should not take to long (?)).

**Comment by DillonJ** [comment]
I think the issue here is that there is the formulation and there is the implementation. It appears that in this instance the formulation was correct and the implementation was correct. The issue was that it was a little difficult in this instance to make the connection between the two. I think this is a developer issue - I feel that a normal user will not necessarily need to understand the implementation of the fomulation. Additionally, there are unit tests that verify that constraints generated are consistent with the formulation.

The question is, do we need to get into implementation details in the documentation and if we do, will that confuse users even more? Perhaps some additional text in the docstring to explain what is happening?

**Comment by manuelma** [comment]
We never want to document implementation details. We want to be able to change the implementation at will, without worrying about updating the documentation at the same time.

**Comment by jkiviluo** [comment]
@manuelma That's wise. So, anything that explains implementation should be in docstrings - and is meant for model coders.

**Comment by manuelma** [comment]
@jkiviluo actually, *docstrings* are meant to documentation and documentation alone. It's a string that you put below or above a function definition where you describe the usage (purpose, parameters, return value, etc). To me, ideally we would describe implementation as *comments* (not the same as docstrings) inline the code itself.

**Comment by tarskul** [comment]
Unless we make different regions in the docstring as suggested as one of the possible design decisions in issue #649 (e.g. #region developernote). That way we can still later decide programmatically whether we want the implementation details in the documentation or not.

**Comment by jkiviluo** [comment]
Sorry if I'm confused, but I think docstrings can be used just as code comments (that, unlike regular comments, can be shown by debugging software). It's only when you follow e.g. Sphinx specific dosctring conventions that they get turned into actual documentation (if you run Sphinx). Anyway, this is not important - what matters is the convention where we're not trying to make 'documentation' of implementation details. Just comments that can help coders.

**Comment by gnawin** [comment]
Thanks all for the lively discussion. I consulted my TNO colleagues about this issue, and indeed, we thought there was some confusion for users like us. 

We'd propose to put the documentation regarding ramping and reserves back, but add the below text at the beginning to acknowledge the issue.

"The current documentation on ramping and reserves is presented in a way that is aligned with the SpineOpt modeling logic and data structure, which may sometimes seem counterintuitive for users who are not familiar with this logic and the data structure. For example, in the current documentation the upward and downward reserves appear in the same equation; however, they will not be activated simultaneously given the modeling logic and data structure of SpineOpt. We are currently improving the formulation to make it more computationally efficient and the documentation clearer. We appreciate your patience as we strive to provide clearer and more helpful information."

We can always decide in what way we want to document (e.g, whether, where, and to what extent we want to include implementation details) later, and it seems to me then can be a separate issue as it will become a more general topic.

What do you think?

**Comment by DillonJ** [comment]
I am now a little confused about the actual issue. So in the documentation, we have the Ramping and Reserves article that deals with this at a functional level here:

https://spine-tools.github.io/SpineOpt.jl/latest/advanced_concepts/ramping_and_reserves/

This article doesn't talk about the formulation, but describes how to do things using the parameters.

Then there is the fomulation - but I can't see how that was because it was removed. Is the issue with the formulation that was written in a way that mirrors how the constraint is implemented in the code? I.e. that the mathematical formulation in the documentaiton has both upward and downward terms along with terms that activate only one at a time depending on the sense?

If that is the case, the mathematical formulation could be restructured to present the indivudual constraints for upwards and downwards reserve. The functional documentation is clear about how to achieve this using the parameters and then by way of comments in the constraint equation code, we can describe how we are efficiently implementing multiple constraints using one constraint julia file (we do this in many other cases in the code, e.g. [ratio_unit_flow] where a single block of code implements `[min/max/fix]_ratio_[in/out]_[in/out]_unit_flow`.

I.e. maybe the mathematical formulation should be free of implementation details. The implementation details can be explained using comments in the code as @manuelma suggests.

Thoughts?

**Comment by nnhjy** [comment]
That's the very significance of restoring the mathematical formulations of the current implementation

> Then there is the fomulation - but I can't see how that was because it was removed.

@gnawin 's proposal from TNO side looks good for now. We could discuss the way to improve the documentation style later on.

As far as I remember, the formulation kinda mirrors the implementation code, which was quite nice as it shows the direct relationship with the implementation code. And as what happened with this issue, people seem to be able to spot the problem of confusion easily. 

It sounds a good idea to make the mathematical formulation free of implementation details. Then the task becomes to show/prove to the readers that the two sides are equivalent. Perhaps there is already some research or this could be a nice gap to study.

**Comment by gnawin** [comment]
Since I made the initial commits, I'd say I will wait for another week (so before next Wednesday) to see if anyone has better/concrete ideas than my proposal. Otherwise I will take the docs back with the texts above.

It is of course a good idea to further clarify the equivalency of the math and the implementation. We can maybe then create a general issue in the future.

**Comment by gnawin** [comment]
As agreed, the documentation on ramping and reserve constraints that was removed has been brought back (see details of commit 2a4d87f).
