### ISSUE TITLE
Abnormal result of the storage node after adding efficiency (fix_ratio_out_in_unit_flow)

### ISSUE THREAD

**Issue by HaoyuFang0909** [spine-tools/SpineOpt.jl#719]
I added a H2 storage based on a GB power system model. It can work properly with defining its efficiency (fix_ratio_out_in_flow) as 1.0. When I changed the efficiency to other numbers (0.7), the state of H2 became abnormal, as shown in the picture below. 

I would appreciate it if you could help correct the error.

Model of the H2 storage: 
![image](https://github.com/spine-tools/SpineOpt.jl/assets/126673775/c90f9dd0-8996-4916-86ff-9eba50bfc701)
Results:
![image](https://github.com/spine-tools/SpineOpt.jl/assets/126673775/527ffc17-c287-4c6d-99c7-1cc914a71695)
![image](https://github.com/spine-tools/SpineOpt.jl/assets/126673775/4c5e3a23-28cb-464c-b63a-211c07e4b310)

**Comment by DillonJ** [comment]
Hi @HaoyuFang0909 

It's hard to diagnose your issue without knowing what's going on in the rest of your model. If you'd like to upload your model sqlite file (zipped to get around githubs restrictions) then I could take a look. But my initial suspicions are that now you have reduced the efficiency, this is the optimal result given the other parameters in the model (which we can't see) or you have some combination of parameters making it impossible for the storage state to change.

**Comment by HaoyuFang0909** [comment]
Sure! The model is attached below. Also I would like to know how I can demonstrate the flexibility of the H2 storage by modelling in Spine. 
Thanks!
[Generator_databasev2023_06_02.zip](https://github.com/spine-tools/SpineOpt.jl/files/12249876/Generator_databasev2023_06_02.zip)

**Comment by DillonJ** [comment]
I just took a look at your model - and there is quite a lot going on. You lowered the efficiency of the electrolyser to from 1 to 0.7 and your result shows that the storage is not utilized. I wouldn't describe this as abnormal or not working, it seems to simply be your result, the storage is simply not utilized because it is not optimal to use it given the rest of the system. You can validate the result by testing different efficiency values... e.g. 0.95.

Are you sure about your units and conversions?

It seems like you have used efficienies for your conventional plant meaning that your units of fuel are MWh. 

Therefore, your fuel prices are in the units of £ per MWh

I'm not sure what units you have used for your Co2 emission factors - but your CCGT plant has a value of 0.51

Your Carbon price is 10 meaning that for your CCGT plant, one MWh of gas consumed will cost 10 * 0.51 = £5.1 / MWh or £1.42 / GJ.

A 100 EUR/ton carbon price is equivalent to roughly 5.7 Eur / GJ of gas consumed, so perhaps your low carbon price means electrolysis is not competitive in your system?



Your carbon emission factors seem to be in the units of 

Your carbon price is quite low at 10. Given your

**Comment by HaoyuFang0909** [comment]
Hi @DillonJ 
Thanks for your advice! You are right. The low efficiency of the storage leads to more fuel costs, so the storage is not used. The storage will be used if I set the efficiency very high.
