### ISSUE TITLE
Questions on investment optimisation

### ISSUE THREAD

**Issue by HaoyuFang0909** [spine-tools/SpineOpt.jl#723]
For a unit (or storage) the unit_investment_cost is the investment cost per candidate unit over its unit_investment_lifetime. For the model horizon of 1 year, if I set the unit_investment_lifetime as 20 years, the unit_investment_cost should be the annualised investment cost or the total 20-year investment cost?

**Comment by DillonJ** [comment]
Hi @HaoyuFang0909 

Currently there is no connection between `*_investment_cost ` and  `*_investment_lifetime` although this is being considered as part of https://github.com/spine-tools/SpineOpt.jl/pull/448

Right now `*_investment_cost ` is the total investment cost per investment `*_investment_lifetime` simply enforces that once an investment is made, it remains in force for at least this amount of time.

Therefore, in the currently implementation, you have to make sure you investment cost is consistent with your modelling horizon. For example, if you are modelling a single year, it would be recommended to make sure that your investment cost is the annualised cost. Rather than using `*_investment_lifetime` which impacts performance quite significantly, I would recommend indead using a temporal resolution of 1y for your investment temporal block.

**Comment by HaoyuFang0909** [comment]
Thanks for your timely response! @DillonJ 
So it seems *_investment_lifetime is not important for one-time investment as long as it covers the model horizon.
