### ISSUE TITLE
Add an expression for capacity_margin and a minimum capacity margin constraint to allow scheduling of outages

### ISSUE THREAD

**Issue by DillonJ** [spine-tools/SpineOpt.jl#920]
With #903 we can now schedule maintenance outages. At present, feasibility and cost will be the only factors influencing the optimality of the scheduled outages. If we implement capacity margin as an expression, this allows adequacy to influence the decision. For example, we can define a minimum capacity margin that is penalised - this will force the model to schedule outages while respecting a minimum level of reliability and opens the door for more comprehensive treatments of adequacy.

**Comment by clizbe** [comment]
@DillonJ Is this part of the updates you said you're working on in relation to another project?
In principal I think it's fine to add an expression (since it's not a variable), but in general I think we should focus on our major changes and leave adding smaller details like this (that also add constraints) until after we get the core and speed taken care of.

**Comment by clizbe** [comment]
Closed by #924
